### ISSUE TITLE
Fail to detect WeMo Switch with firmware WeMo_WW_2.00.10062.PVT-OWRT-SNS

### ISSUE THREAD

**Issue by vejuhust** [iancmcc/ouimeaux#118]
ouimeaux works really well with the previous firmware, but it can't detect my WeMo Switch after upgrading firmware. Restoring to factory setting doesn't help.

**Comment by yonib05** [comment]
+1

**Comment by jetpacktuxedo** [comment]
I seem to be having the same issue with WeMo_WW_2.00.10062.PVT-OWRT-InsightV2. If I run wemo -f list about a dozen times I will get a response once or twice in there. Increasing the timeout doesn't seem to help, it will either respond instantly or not at all.

**Comment by iancmcc** [comment]
Heck, ok, I'll try to look at this as soon as I can.

**Comment by renkoh** [comment]
From the Belkin forum, may aid in fixing the issue:

"I believe the problem is related to a change in the way the latest firmware for the WeMo switches responds (or not) to the SSDP discovery packet. Unless the source port is set to 1900 as well as the destination port, the WeMo's now ignore the discovery broadcast.  Could someone please confirm this with Belkin and find out if their code will stay this way or if they will revert to their earlier implementation?"

hanging out for a fix!
