### ISSUE TITLE
Manual input for Wemo device list

### ISSUE THREAD

**Issue by 0HFgX1pM8hUbvsCpAl3D** [iancmcc/ouimeaux#182]
Is there a way to manually query devices knowing their IPs? Mine decided to stop responding to M-SEARCH requests.

**Comment by BlackLight** [comment]
Same issue here. After one of the latest firmware upgrades, ouimeaux won't get M_SEARCH responses anymore from my devices (tested on multiple computers and with multiple devices), even though things still work fine from the mobile app.

Something is probably wrong on the protocol side, but as a workaround it'd be great to have the possibility to specify the devices by IP/hostname instead of doing a discovery every time, even if they haven't been cached yet.
