### ISSUE TITLE
Split ouimeaux into a core and add-ons

### ISSUE THREAD

**Issue by balloob** [iancmcc/ouimeaux#32]
I think that ouimeaux should be split up into a core part that provides the API: the WeMo communication and discovery and split into a second part that hosts a server or provides a command-line interface. That way we can greatly reduce the dependencies for other programs that depend on ouimeaux and that do not need the use of flask or the command-line. 

To see if it is possible I created a stripped down version of ouimeaux [here](https://github.com/balloob/pywemo). I replaced the uPnP part with my own implementation that has no external dependencies. The stripped down version only depends on `requests`. I did not port the motion part because I do not have one at hand to test it.

**Comment by daveb1014** [comment]
Hi all,

Ouimeaux works great, thank you for an awesome program.

However, after running for a day or so, my switches begin to drop off, and if I run:

wemo clear
wemo -t 15 list

I can only see some switches, and others begin to give errors like:

File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/adapters.py", line 419, in send
   raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='192.168.0.54', port=49154): Max retries exceeded with url: /setup.xml (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x2d35d90>, 'Connection to 192.168.0.54 timed out. (connect timeout=1)'))
<Greenlet at 0x2b64cd0: <bound method Signal.send of <pysignals.dispatcher.Signal object at 0x2772790>>(<ouimeaux.discovery.UPnP object at 0x2b8f550>, headers={'opt': '"http://schemas.upnp.org/upnp/1/0/"; ns=0, address=('192.168.0.54', 3527))> failed with ConnectTimeout

Eventually, after a couple of days, all switches start to report this error. I have to reset my wireless access point and restart wemo and clear the cache to get it going for another couple of days. Does anybody know what is going on with the connection failures here? Running on raspbian on a raspberry pi, also tested (with the same result) on centos 7.0.1406

**Comment by fingon** [comment]
Feel free to start a new issue on this; in my experience, WeMos require lots of handholding (e.g. periodic rediscovery and so on) and even doing that then they sometimes (but very rarely, perhaps once every month or two) fall off the map. That said, my own (non-ouimeaux) code seems to have kept track of events successfully for soon month in row, with only one oddity (one of the WeMo switches started turning itself on and off rapidly; power cycle fixed that) :p

**Comment by balloob** [comment]
@daveb1014 the issue you report is a duplicate of #55

**Comment by daveb1014** [comment]
Thank you, so I see it is... unfortunately I opened #74 before I noticed your comment, I have closed that now.

**Comment by iancmcc** [comment]
Finally getting somewhere with this. Instead of separate packages entirely, I'm using features. So ``pip install ouimeaux[server]`` to get the server, but ``pip install ouimeaux`` will just get the basic library and cli.

Also currently working on getting rid of the gevent dependency.

**Comment by iancmcc** [comment]
https://github.com/iancmcc/ouimeaux/commit/8e1aa1ad3cb08429f26bd87fa37f73129d7b6312

**Comment by balloob** [comment]
This is awesome, thanks @iancmcc . I'm looking forward to switch [home assistant](https://github.com/balloob/home-assistant) to use ouimeaux.
