### ISSUE TITLE
help setting up the api for windows 

### ISSUE THREAD

**Issue by BOF007** [iancmcc/ouimeaux#95]
http://stackoverflow.com/questions/31500489/wemo-and-python-incorporation-for-a-beginner/31501087#31501087

also i running python 3.4 is that a problem ?

**Comment by iancmcc** [comment]
Yes, ouimeaux is not compatible with Python 3, because several of its
dependencies are not compatible. You should certainly be running Python 2.

There's no particular reason it won't run on Windows, just make sure to
follow the installation instructions for Windows, which are, I believe,
slightly different. A helpful community member got it working on Windows; I
don't have a Windows box myself to try it on.

**Comment by BOF007** [comment]
is there a way to run both py 2 and 3 so I have the main prgm in 3 but when it needs to communicate with the wemo program 


if its not possible 


could you make a quick py 3 code just for the insight switch and the switch on / off / cycle is all I need I would even compensate you for your time 






Sent from Windows Mail





From: Ian McCracken
Sent: ‎Sunday‎, ‎July‎ ‎19‎, ‎2015 ‎9‎:‎14‎ ‎AM
To: iancmcc/ouimeaux
Cc: BOF007




Yes, ouimeaux is not compatible with Python 3, because several of its
dependencies are not compatible. You should certainly be running Python 2.

There's no particular reason it won't run on Windows, just make sure to
follow the installation instructions for Windows, which are, I believe,
slightly different. A helpful community member got it working on Windows; I
don't have a Windows box myself to try it on.

**Comment by iancmcc** [comment]
Sure, you can run ouimeaux in python 2.7 and whatever else in python 3, if you communicate over the REST API rather than at the domain level. You of course can not run them in the same process.

One cannot rewrite only part of ouimeaux. The dependency in particular that is not (yet) Py3 compatible is gevent (although I believe that support is in alpha). Properly, ouimeaux would be rewritten to use Guido's asyncio package in Python 3, which would then be roughly ready for the async/await keywords coming in 3.7. It won't be soon, though.
